=== nigeleke/tolke/core/test/fixtures/schemas/v0/tests.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/unicode-org/message-format-wg/main/test/schemas/v0/tests.schema.json",
    "title": "Unicode MessageFormat data-driven tests",
    "description": "The main schema for Unicode MessageFormat test data.",
    "type": "object",
    "additionalProperties": false,
    "required": ["tests"],
    "properties": {
        "$schema": {
            "type": "string",
            "description": "Identifier for the test file JSON schema."
        },
        "scenario": {
            "type": "string",
            "description": "Identifier for the tests in the file."
        },
        "description": {
            "type": "string",
            "description": "Information about the test scenario."
        },
        "defaultTestProperties": {
            "$ref": "#/$defs/defaultTestProperties"
        },
        "tests": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/test"
            },
            "minItems": 1
        }
    },
    "$comment": "This allOf specifies required test properties that allow a default. A value will be required in 'defaultTestProperties' if one is not provided for every individual test.",
    "allOf": [
        {
            "anyOf": [
                {
                    "properties": {
                        "defaultTestProperties": {
                            "type": "object",
                            "required": ["locale"]
                        }
                    }
                },
                {
                    "properties": {
                        "tests": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "required": ["locale"]
                            }
                        }
                    }
                }
            ]
        },
        {
            "anyOf": [
                {
                    "properties": {
                        "defaultTestProperties": {
                            "type": "object",
                            "required": ["src"]
                        }
                    }
                },
                {
                    "properties": {
                        "tests": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "required": ["src"]
                            }
                        }
                    }
                }
            ]
        },
        {
            "$comment": "Only one assertion is required. It doesn't matter which type.",
            "anyOf": [
                {
                    "properties": {
                        "defaultTestProperties": {
                            "$ref": "#/$defs/anyExp"
                        }
                    }
                },
                {
                    "properties": {
                        "tests": {
                            "type": "array",
                            "items": {
                                "$ref": "#/$defs/anyExp"
                            }
                        }
                    }
                }
            ]
        }
    ],
    "$defs": {
        "defaultTestProperties": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "locale": {
                    "$ref": "#/$defs/locale"
                },
                "src": {
                    "$ref": "#/$defs/src"
                },
                "bidiIsolation": {
                    "$ref": "#/$defs/bidiIsolation"
                },
                "params": {
                    "$ref": "#/$defs/params"
                },
                "tags": {
                    "$ref": "#/$defs/tags"
                },
                "exp": {
                    "$ref": "#/$defs/exp"
                },
                "expParts": {
                    "$ref": "#/$defs/expParts"
                },
                "expErrors": {
                    "$ref": "#/$defs/expErrors"
                }
            }
        },
        "test": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "description": {
                    "type": "string",
                    "description": "Information about the test."
                },
                "locale": {
                    "$ref": "#/$defs/locale"
                },
                "src": {
                    "$ref": "#/$defs/src"
                },
                "bidiIsolation": {
                    "$ref": "#/$defs/bidiIsolation"
                },
                "params": {
                    "$ref": "#/$defs/params"
                },
                "tags": {
                    "$ref": "#/$defs/tags"
                },
                "exp": {
                    "$ref": "#/$defs/exp"
                },
                "expParts": {
                    "$ref": "#/$defs/expParts"
                },
                "expErrors": {
                    "$ref": "#/$defs/expErrors"
                },
                "only": {
                    "type": "boolean",
                    "description": "Normally not set. A flag to use during development to only run one or more specific tests."
                }
            }
        },
        "locale": {
            "description": "The locale to use for formatting.",
            "type": "string"
        },
        "src": {
            "description": "The message source in the Unicode MessageFormat syntax.",
            "type": "string"
        },
        "bidiIsolation": {
            "description": "The bidi isolation strategy.",
            "enum": ["default", "none"]
        },
        "params": {
            "description": "Parameters to pass in to the formatter for resolving external variables.",
            "type": "array",
            "items": {
                "$ref": "#/$defs/var"
            }
        },
        "tags": {
            "description": "List of features that the test relies on.",
            "type": "array",
            "items": {
                "enum": [":currency", ":percent", "u:dir", "u:id"]
            }
        },
        "var": {
            "type": "object",
            "oneOf": [
                {
                    "additionalProperties": false,
                    "required": ["name", "value"],
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "value": {}
                    }
                },
                {
                    "additionalProperties": false,
                    "required": ["name", "type", "value"],
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "type": {
                            "const": "datetime"
                        },
                        "value": {
                            "$comment": "Should be converted to a datetime.",
                            "type": "string"
                        }
                    }
                }
            ]
        },
        "exp": {
            "description": "The expected result of formatting the message to a string.",
            "type": "string"
        },
        "expParts": {
            "description": "The expected result of formatting the message to parts.",
            "type": "array",
            "items": {
                "oneOf": [
                    {
                        "description": "Message text part.",
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["type", "value"],
                        "properties": {
                            "type": {
                                "const": "text"
                            },
                            "value": {
                                "type": "string"
                            }
                        }
                    },
                    {
                        "description": "Bidi isolation part.",
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["type", "value"],
                        "properties": {
                            "type": {
                                "const": "bidiIsolation"
                            },
                            "value": {
                                "enum": ["\u2066", "\u2067", "\u2068", "\u2069"]
                            }
                        }
                    },
                    {
                        "description": "Message markup part.",
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["type", "kind", "name"],
                        "properties": {
                            "type": {
                                "const": "markup"
                            },
                            "kind": {
                                "enum": ["open", "standalone", "close"]
                            },
                            "name": {
                                "type": "string"
                            },
                            "id": {
                                "type": "string"
                            },
                            "options": {
                                "type": "object"
                            }
                        }
                    },
                    {
                        "description": "Message expression part.",
                        "type": "object",
                        "required": ["type"],
                        "properties": {
                            "type": {
                                "enum": ["datetime", "number", "string", "test"]
                            },
                            "locale": {
                                "type": "string"
                            },
                            "id": {
                                "type": "string"
                            },
                            "parts": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "type": {
                                            "type": "string"
                                        }
                                    },
                                    "required": ["type"]
                                }
                            },
                            "value": {}
                        }
                    },
                    {
                        "description": "Fallback part.",
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["type", "source"],
                        "properties": {
                            "type": {
                                "const": "fallback"
                            },
                            "source": {
                                "type": "string"
                            }
                        }
                    }
                ]
            }
        },
        "expErrors": {
            "description": "The runtime errors expected to be emitted when formatting the message. If expErrors is either absent or empty, the message must be formatted without errors.",
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "required": ["type"],
                "properties": {
                    "type": {
                        "enum": [
                            "syntax-error",
                            "variant-key-mismatch",
                            "missing-fallback-variant",
                            "missing-selector-annotation",
                            "duplicate-declaration",
                            "duplicate-option-name",
                            "duplicate-variant",
                            "unresolved-variable",
                            "unknown-function",
                            "bad-selector",
                            "bad-operand",
                            "bad-option",
                            "bad-variant-key"
                        ]
                    }
                }
            }
        },
        "anyExp": {
            "type": "object",
            "anyOf": [
                {
                    "required": ["exp"]
                },
                {
                    "required": ["expParts"]
                },
                {
                    "required": ["expErrors"]
                }
            ]
        }
    }
}

=== nigeleke/tolke/core/test/fixtures/tests/syntax.json
{
    "$schema": "../schemas/v0/tests.schema.json",
    "scenario": "Syntax",
    "description": "Test cases that do not depend on any registry definitions.",
    "defaultTestProperties": {
        "bidiIsolation": "none",
        "locale": "en-US"
    },
    "tests": [
        {
            "description": "message -> simple-message -> <empty>",
            "src": "",
            "exp": ""
        },
        {
            "description": "message -> simple-message -> simple-start pattern -> simple-start-char",
            "src": "a",
            "exp": "a"
        },
        {
            "description": "message -> simple-message -> simple-start pattern -> simple-start-char pattern -> ...",
            "src": "hello",
            "exp": "hello"
        },
        {
            "description": "message -> simple-message -> simple-start pattern -> escaped-char",
            "src": "\\\\",
            "exp": "\\"
        },
        {
            "description": "message -> simple-message -> simple-start pattern -> 1*escaped-char",
            "src": "\\\\\\{\\|\\}",
            "exp": "\\{|}"
        },
        {
            "description": "message -> simple-message -> simple-start pattern -> simple-start-char pattern -> ... -> simple-start-char *text-char placeholder",
            "src": "hello {world}",
            "exp": "hello world"
        },
        {
            "description": "message -> simple-message -> simple-start pattern -> simple-start-char pattern -> ... -> simple-start-char *text-char placeholder",
            "src": "hello {|world|}",
            "exp": "hello world"
        },
        {
            "description": "message -> simple-message -> s simple-start pattern -> s simple-start-char pattern -> ...",
            "src": "\n hello\t",
            "exp": "\n hello\t"
        },
        {
            "src": "hello {$place}",
            "params": [
                {
                    "name": "place",
                    "value": "world"
                }
            ],
            "exp": "hello world"
        },
        {
            "src": "hello {$place-.}",
            "params": [
                {
                    "name": "place-.",
                    "value": "world"
                }
            ],
            "exp": "hello world"
        },
        {
            "src": "hello {$place}",
            "expErrors": [
                {
                    "type": "unresolved-variable"
                }
            ],
            "exp": "hello {$place}"
        },
        {
            "description": "message -> simple-message -> simple-start pattern -> placeholder -> expression -> literal-expression -> \"{\" literal \"}\"",
            "src": "{a}",
            "exp": "a"
        },
        {
            "description": "... -> literal-expression -> \"{\" literal s annotation \"}\" -> \"{\" literal s function \"}\" -> \"{\" literal s \":\" identifier \"}\" -> \"{\" literal s \":\" name \"}\"",
            "src": "{a :f}",
            "exp": "{|a|}",
            "expErrors": [{ "type": "unknown-function" }],
            "only": true
        },
        {
            "description": "... -> \"{\" literal s \":\" namespace \":\" name \"}\"",
            "src": "{a :u:f}",
            "exp": "{|a|}",
            "expErrors": [{ "type": "unknown-function" }]
        },
        {
            "description": "message -> simple-message -> simple-start pattern -> placeholder -> expression -> variable-expression -> \"{\" variable \"}\"",
            "src": "{$x}",
            "exp": "{$x}",
            "expErrors": [{ "type": "unresolved-variable" }]
        },
        {
            "description": "... -> variable-expression -> \"{\" variable s annotation \"}\" -> \"{\" variable s function \"}\" -> \"{\" variable s \":\" identifier \"}\" -> \"{\" variable s \":\" name \"}\"",
            "src": "{$x :f}",
            "exp": "{$x}",
            "expErrors": [
                { "type": "unresolved-variable" },
                { "type": "unknown-function" }
            ]
        },
        {
            "description": "... -> \"{\" variable s \":\" namespace \":\" name \"}\"",
            "src": "{$x :u:f}",
            "exp": "{$x}",
            "expErrors": [
                { "type": "unresolved-variable" },
                { "type": "unknown-function" }
            ]
        },
        {
            "description": "... -> annotation-expression -> function -> \"{\" \":\" namespace \":\" name \"}\"",
            "src": "{:u:f}",
            "exp": "{:u:f}",
            "expErrors": [{ "type": "unknown-function" }]
        },
        {
            "description": "... -> annotation-expression -> function -> \"{\" \":\" name \"}\"",
            "src": "{:f}",
            "exp": "{:f}",
            "expErrors": [{ "type": "unknown-function" }]
        },
        {
            "description": "message -> complex-message -> complex-body -> quoted-pattern -> \"{{\" pattern \"}}\" -> \"{{\"\"}}\"",
            "src": "{{}}",
            "exp": ""
        },
        {
            "description": "message -> simple-message -> simple-start pattern -> placeholder -> markup -> \"{\" \"#\" identifier \"}\"",
            "src": "{#tag}",
            "exp": "",
            "expParts": [
                {
                    "type": "markup",
                    "kind": "open",
                    "name": "tag"
                }
            ]
        },
        {
            "description": "message -> complex-message -> *(declaration [s]) complex-body -> declaration complex-body -> input-declaration complex-body -> input variable-expression complex-body",
            "src": ".input{$x}{{}}",
            "exp": ""
        },
        {
            "description": "message -> complex-message -> s *(declaration [s]) complex-body s -> s declaration complex-body s -> s input-declaration complex-body s -> s input variable-expression complex-body s",
            "src": "\t.input{$x}{{}}\n",
            "exp": ""
        },
        {
            "description": "message -> complex-message -> *(declaration [s]) complex-body -> declaration declaration complex-body -> input-declaration input-declaration complex-body -> input variable-expression input variable-expression complex-body",
            "src": ".input{$x}.input{$y}{{}}",
            "exp": ""
        },
        {
            "description": "message -> complex-message -> *(declaration [s]) complex-body -> declaration s declaration complex-body -> input-declaration s input-declaration complex-body -> input variable-expression s input variable-expression complex-body",
            "src": ".input{$x} .input{$y}{{}}",
            "exp": ""
        },
        {
            "description": "message -> complex-message -> s *(declaration [s]) complex-body s -> s complex-body s",
            "src": "  {{}}  ",
            "exp": ""
        },
        {
            "description": "message -> complex-message -> *(declaration [s]) complex-body -> declaration declaration complex-body -> local-declaration input-declaration complex-body -> local s variable [s] \"=\" [s] expression input variable-expression complex-body",
            "src": ".local $x ={a}.input{$y}{{}}",
            "exp": ""
        },
        {
            "description": "message -> complex-message -> complex-body -> ... -> matcher -> match-statement variant -> match selector key quoted-pattern -> \".match\" variable literal quoted-pattern",
            "src": ".local $a={a :f}.match $a a{{}}*{{}}",
            "exp": "",
            "expErrors": [
                { "type": "unknown-function" },
                { "type": "bad-selector" }
            ]
        },
        {
            "description": "... input-declaration -> input s variable-expression ...",
            "src": ".input {$x}{{}}",
            "exp": ""
        },
        {
            "description": "... local-declaration -> local s variable s \"=\" expression ...",
            "src": ".local $x ={a}{{}}",
            "exp": ""
        },
        {
            "description": "... local-declaration -> local s variable \"=\" s expression ...",
            "src": ".local $x= {a}{{}}",
            "exp": ""
        },
        {
            "description": "... local-declaration -> local s variable s \"=\" expression ...",
            "src": ".local $x = {a}{{}}",
            "exp": ""
        },
        {
            "description": "input-declaration-like content in complex-message",
            "src": "{{.input {$x}}}",
            "params": [{ "name": "x", "value": "X" }],
            "exp": ".input X"
        },
        {
            "description": "local-declaration-like content in complex-message with leading whitespace",
            "src": "{{ .local $x = {$y}}}",
            "params": [{ "name": "y", "value": "Y" }],
            "exp": " .local $x = Y"
        },
        {
            "description": "... matcher -> match-statement [s] variant -> match 1*([s] selector) variant -> match selector selector variant -> match selector selector variant key s key quoted-pattern",
            "src": ".local $a={a :f}.local $b={b :f}.match $a $b a b{{}}* *{{}}",
            "exp": "",
            "expErrors": [
                { "type": "unknown-function" },
                { "type": "bad-selector" },
                { "type": "unknown-function" },
                { "type": "bad-selector" }
            ]
        },
        {
            "description": "... matcher -> match-statement [s] variant -> match 1*([s] selector) variant -> match selector variant variant ...",
            "src": ".local $a={a :f}.match $a a{{}}b{{}}*{{}}",
            "exp": "",
            "expErrors": [
                { "type": "unknown-function" },
                { "type": "bad-selector" }
            ]
        },
        {
            "description": "... variant -> key s quoted-pattern -> ...",
            "src": ".local $a={a :f}.match $a a {{}}*{{}}",
            "exp": "",
